import type { Metadata } from "next";
import "./globals.css";
import LoadingProvider from "@/components/provider/LoadingProvider";
import ModalProvider from "@/components/provider/ModalProvider";
import TemplateNavChecker from "@/components/template/TemplateNavChecker";
import { Homemade_Apple } from "next/font/google";
import { getPopularProject } from "@/libs/fetchs/fetchProject";

const homemadeApple = Homemade_Apple({
  weight: "400",
  style: "normal",
  preload: true,
  subsets: ["latin"],
  variable: "--font-homemade-apple",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const popularProject = (await getPopularProject()) || [];
  return (
    <html lang="in" translate="no">
      <body className={`${homemadeApple.variable}`}>
        <LoadingProvider>
          <ModalProvider>
            <TemplateNavChecker data={popularProject}>
              {children}
            </TemplateNavChecker>
          </ModalProvider>
        </LoadingProvider>
      </body>
    </html>
  );
}
